INSERT INTO `quiz`.`student` (`id`, `first_name`, `last_name`, `password`,`username`) VALUES ('1', 'student', 'name', '$2a$10$OEY1lDCNH/jEB8FQS/Jgwejry9.YhqEslkeDMtF5MQzFUrQiU/gra','user@gmail.com');

INSERT INTO `quiz`.`school` (`id`, `password`, `school_name`, `username`) VALUES ('1', '$2a$10$OEY1lDCNH/jEB8FQS/Jgwejry9.YhqEslkeDMtF5MQzFUrQiU/gra', 'school', 'school@gmail.com');


INSERT INTO `quiz`.`quiz` (`id`, `quiz_name`) VALUES ('1', 'AngularJS Online Quiz');



INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', 'It is a software Code that stores the data', 'It is a software Code that renders the user interface', 'It is a software Code that controls the interactions between the Model and View', 'None of the above.', 'What is a controller in MVC?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'd', 'ng-required', 'ng-minlength', 'ng-pattern', 'All of the above', 'Which of the followings are validation directives?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'a', 'Application Module', 'constant', 'value', 'factory', 'Which components can be injected as a dependency in AngularJS?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', 'Brad Green', ' Igor Minor', 'Misko Hevery', 'Brian Ford', 'Who is sometimes called as Father of AngularJS?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'b', 'Expressions behave in same way as ng-bind directives', 'All of these', 'Expressions are written inside double braces like {{ expression}}', 'Expressions are used to bind application data to html', 'Which of the following is true about AngularJS expressions', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'a', 'angular.module();', ' var myModule = new module();', 'module.create();', 'angular.create();', ' AngularJS module can be created using ________', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'a', ' It is used for registering DOM listeners as well as instance DOM manipulation', 'It is used to retrieve object instances as defined by provider', 'It is used for template DOM Manipulation and collect all of the directives', 'The method traverses the DOM and matches the directives', 'What is link function is used for in angular js?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', 'DOMContentLoaded event happens', 'document.readyState is set to complete', 'Both of the above.', 'None of the above.', 'Angular initializes based upon which of the following scenario?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'a', 'double braces like {{ expression}}', 'single braces like {expression}', 'small bracket like (expression)', 'capital bracket like [expression]', 'AngularJS expressions are written using.', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'a', 'angular.bootstrap', 'angular.element', 'angular.copy', 'None of the above.', ' What angular function is used to manually start up an angular application?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'b', 'Model', 'View', 'Controller', 'Module', 'AngularJS directives are used in ________', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'd', 'Typically using the new operator, dependency can be created', 'By referring to a global variable, dependency can be looked up', 'Dependency can be passed into where it is required', 'All of the above', 'How does an object or function can get hold of its dependencies in angular js?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', '$param', '$control', '$scope', '$scont', 'There is a controller which takes a single parameter. We call it . . . . . parameter.', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'b', ' ng-include', 'ng-form', 'ng-bind', 'ng-attach', 'Which of the following directive allows us to use form?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'd', 'JavaScript file is loaded', 'The angular global object is created', 'Your JavaScript which registers controller functions is executed', 'All of above', ' In AngulsrJS HTML document is loaded and evaluated first in the browser. Mean while in AngularJS _________ ?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', 'ng-, data-ng-, ng:, ng-', 'ng-, data-ng-', 'ng:', 'x-ng-.,ng-, data-ng-,x-ng-', 'What are various possible prefixes such as ng- using which Angular directives (for example, ng-app) can be defined?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', 'false', 'true', 'All of the above', 'None of the above.', 'Is AngularJS extensible?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', 'Yes.', 'No', 'Both of the above.', 'None of the above.', 'Which of the following is true about ng-app directive?', '1');
INSERT INTO `quiz`.`questions` (`id`, `answer`, `a`, `b`, `c`, `d`, `question`, `fk_quiz_id`) VALUES ('0', 'c', 'ng-app directive defines and links an AngularJS application to HTML.', 'ng-app directive indicates the start of the application.', 'Both of the above.', 'None of the above.', 'Which of the following is true about ng-app directive?', '1');